name: "AI Consultant Agent"

on:
  push:
    paths:
      - 'agents/ai-consultant-agent/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libffi-dev

      - name: Install pip and poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install agent dependencies
        run: |
          cd agents/ai-consultant-agent
          pip install -r requirements.txt
          pip install google-adk absl-py python-dotenv

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install ai-consultant-agent package
        run: |
          cd agents/ai-consultant-agent
          pip install -e .

      - name: Deploy AI Consultant Agent to Vertex AI
        env:
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          REGION: us-central1  # Override region just for agent deployment
          GCP_BUCKET: ${{ vars.GCP_BUCKET }}
        run: |
          cd agents/ai-consultant-agent/deployment
          python deploy.py --create --project_id $PROJECT_ID --location us-central1 --bucket $GCP_BUCKET

      - name: Upload agent resource file for server
        uses: actions/upload-artifact@v4
        with:
          name: agent_resource
          path: agents/ai-consultant-agent/deployment/agent_resource.txt

  trigger-server-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.trigger_server_deploy == 'true' }}
    steps:
      - name: Trigger manual server deploy
        uses: peter-evans/workflow-dispatch@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: server-deploy.yml
          ref: ${{ github.ref }}
