name: "AI Consultant Agent"

on:
  push:
    paths:
      - 'agents/ai-consultant-agent/**'
  workflow_dispatch:
    inputs:
      trigger_server_deploy:
        description: 'Trigger server deployment?'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libffi-dev

      - name: Install pip and poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install agent dependencies
        run: |
          cd agents/ai-consultant-agent
          pip install -r requirements.txt
          pip install google-adk absl-py python-dotenv

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install ai-consultant-agent package
        run: |
          cd agents/ai-consultant-agent
          pip install -e .

      - name: Deploy AI Consultant Agent to Vertex AI
        env:
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          REGION: us-central1  # Override region just for agent deployment
          GCP_BUCKET: ${{ vars.GCP_BUCKET }}
        run: |
          cd agents/ai-consultant-agent/deployment
          python deploy.py --create --project_id $PROJECT_ID --location us-central1 --bucket $GCP_BUCKET

      # Upload the artifact with a consistent name for cross-workflow use
      - name: Upload agent resource file for server
        uses: actions/upload-artifact@v4
        with:
          name: agent_resource
          path: agents/ai-consultant-agent/deployment/agent_resource.txt
          retention-days: 1  # Keep it for a short time since it's just for workflow handoff

  trigger-server-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.trigger_server_deploy == 'true' }}
    steps:
      - name: Trigger server-deploy workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'server-deploy.yml',
              ref: context.ref
            })

      # Add a small delay to ensure the workflow is registered
      - name: Wait for workflow trigger to propagate
        run: sleep 5

      # Create a signal file indicating that we're waiting for server deployment
      - name: Signal waiting for server deployment
        run: |
          echo "Waiting for server deployment to complete before cleanup" > waiting_for_server.txt

      # Upload this as an artifact to track state
      - name: Upload waiting status
        uses: actions/upload-artifact@v4
        with:
          name: waiting_for_server
          path: waiting_for_server.txt
          retention-days: 1