name: Deploy AI Consultant Agent to Vertex AI

on:
  push:
    paths:
      - 'agents/ai-consultant-agent/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libffi-dev

      - name: Install pip and poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install agent dependencies
        run: |
          cd agents/ai-consultant-agent
          pip install -r requirements.txt
          pip install google-adk absl-py python-dotenv

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy AI Consultant Agent to Vertex AI
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_CLOUD_LOCATION: ${{ secrets.GCP_LOCATION }}
          GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
        run: |
          cd agents/ai-consultant-agent/deployment
          python deploy.py --create --project_id $PROJECT_ID --location $GOOGLE_CLOUD_LOCATION --bucket $GCP_BUCKET
