name: Jetbrains Plugin

on:
  push:
    paths:
      - 'intelij-plugin/**'
    branches: [main]
  pull_request:
    paths:
      - 'intelij-plugin/**'
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional)'
        required: false
        type: string

# Cancel previous runs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # Always run build job for all trigger types
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: intelij-plugin

      - name: Build plugin
        run: ./gradlew clean build
        working-directory: intelij-plugin
        env:
          BAID_CLIENT_ID: ${{ secrets.BAID_CLIENT_ID }}
          BAID_REDIRECT_URI: ${{ secrets.BAID_REDIRECT_URI }}
          BAID_AUTH_ENDPOINT: ${{ secrets.BAID_AUTH_ENDPOINT }}
          BAID_SCOPE: ${{ secrets.BAID_SCOPE }}
          BAID_ACCESS_TYPE: ${{ secrets.BAID_ACCESS_TYPE }}
          BAID_PROMPT: ${{ secrets.BAID_PROMPT }}
          BAID_BACKEND_URL: ${{ secrets.BAID_BACKEND_URL }}
          BAID_API_ENDPOINT: ${{ secrets.BAID_API_ENDPOINT }}
          BAID_BACKEND_TOKEN_KEY: ${{ secrets.BAID_BACKEND_TOKEN_KEY }}
          BAID_TOKEN_EXPIRY_KEY: ${{ secrets.BAID_TOKEN_EXPIRY_KEY }}

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-package
          path: intelij-plugin/build/distributions/*.zip
          retention-days: 7

  # COMMENTED OUT: Test job (uncomment if needed in future)
  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Set up JDK 21
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: '21'
  #         distribution: 'temurin'
  #
  #     - name: Grant execute permission for gradlew
  #       run: chmod +x ./gradlew
  #       working-directory: intelij-plugin
  #
  #     - name: Run tests
  #       run: ./gradlew test check
  #       working-directory: intelij-plugin
  #       env:
  #         BAID_CLIENT_ID: ${{ secrets.BAID_CLIENT_ID }}
  #         BAID_REDIRECT_URI: ${{ secrets.BAID_REDIRECT_URI }}
  #         BAID_AUTH_ENDPOINT: ${{ secrets.BAID_AUTH_ENDPOINT }}
  #         BAID_SCOPE: ${{ secrets.BAID_SCOPE }}
  #         BAID_ACCESS_TYPE: ${{ secrets.BAID_ACCESS_TYPE }}
  #         BAID_PROMPT: ${{ secrets.BAID_PROMPT }}
  #         BAID_BACKEND_URL: ${{ secrets.BAID_BACKEND_URL }}
  #         BAID_API_ENDPOINT: ${{ secrets.BAID_API_ENDPOINT }}
  #         BAID_BACKEND_TOKEN_KEY: ${{ secrets.BAID_BACKEND_TOKEN_KEY }}
  #         BAID_TOKEN_EXPIRY_KEY: ${{ secrets.BAID_TOKEN_EXPIRY_KEY }}

  # COMMENTED OUT: Verify job (uncomment if needed in future)
  # verify:
  #   runs-on: ubuntu-latest
  #   needs: build  # Changed from 'test' to 'build'
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Set up JDK 21
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: '21'
  #         distribution: 'temurin'
  #
  #     - name: Grant execute permission for gradlew
  #       run: chmod +x ./gradlew
  #       working-directory: intelij-plugin
  #
  #     - name: Verify plugin compatibility
  #       run: ./gradlew verifyPlugin verifyPluginStructure verifyPluginSignature
  #       working-directory: intelij-plugin
  #       env:
  #         BAID_CLIENT_ID: ${{ secrets.BAID_CLIENT_ID }}
  #         BAID_REDIRECT_URI: ${{ secrets.BAID_REDIRECT_URI }}
  #         BAID_AUTH_ENDPOINT: ${{ secrets.BAID_AUTH_ENDPOINT }}
  #         BAID_SCOPE: ${{ secrets.BAID_SCOPE }}
  #         BAID_ACCESS_TYPE: ${{ secrets.BAID_ACCESS_TYPE }}
  #         BAID_PROMPT: ${{ secrets.BAID_PROMPT }}
  #         BAID_BACKEND_URL: ${{ secrets.BAID_BACKEND_URL }}
  #         BAID_API_ENDPOINT: ${{ secrets.BAID_API_ENDPOINT }}
  #         BAID_BACKEND_TOKEN_KEY: ${{ secrets.BAID_BACKEND_TOKEN_KEY }}
  #         BAID_TOKEN_EXPIRY_KEY: ${{ secrets.BAID_TOKEN_EXPIRY_KEY }}

  publish:
    runs-on: ubuntu-latest
    needs: build  # This ensures build job completes first
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: intelij-plugin

      # Download the artifact from build job
      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-package
          path: intelij-plugin/build/distributions/

      - name: Publish to JetBrains Marketplace
        run: ./gradlew publishPlugin
        working-directory: intelij-plugin
        env:
          INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
          BAID_CLIENT_ID: ${{ secrets.BAID_CLIENT_ID }}
          BAID_REDIRECT_URI: ${{ secrets.BAID_REDIRECT_URI }}
          BAID_AUTH_ENDPOINT: ${{ secrets.BAID_AUTH_ENDPOINT }}
          BAID_SCOPE: ${{ secrets.BAID_SCOPE }}
          BAID_ACCESS_TYPE: ${{ secrets.BAID_ACCESS_TYPE }}
          BAID_PROMPT: ${{ secrets.BAID_PROMPT }}
          BAID_BACKEND_URL: ${{ secrets.BAID_BACKEND_URL }}
          BAID_API_ENDPOINT: ${{ secrets.BAID_API_ENDPOINT }}
          BAID_BACKEND_TOKEN_KEY: ${{ secrets.BAID_BACKEND_TOKEN_KEY }}
          BAID_TOKEN_EXPIRY_KEY: ${{ secrets.BAID_TOKEN_EXPIRY_KEY }}

  release:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4

      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-package
          path: ./artifacts/

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version || '1.1.2' }}
          release_name: Baid Plugin v${{ github.event.inputs.version || '1.1.2' }}
          body: |
            ## Baid Plugin Release v${{ github.event.inputs.version || '1.1.2' }}
            
            ### What's New
            - Fixed deprecated API usage warnings
            - Updated to latest IntelliJ Platform compatibility (2025.1+)
            - Improved URL handling with modern URI approach
            - Enhanced plugin stability and performance
            - Plugin now requires IDE restart on update for better stability
            
            ### Installation
            Install directly from JetBrains Marketplace or download the plugin ZIP file.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/Baid-${{ github.event.inputs.version || '1.1.2' }}.zip
          asset_name: Baid-${{ github.event.inputs.version || '1.1.2' }}.zip
          asset_content_type: application/zip