name: Build, Test, Verify, and Publish JetBrains Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: intelij-plugin
      - name: Build with Gradle
        run: ./gradlew buildPlugin
        working-directory: intelij-plugin
      - name: Run tests
        run: ./gradlew test
        working-directory: intelij-plugin
      - name: Verify plugin
        run: ./gradlew verifyPlugin
        working-directory: intelij-plugin
      - name: Publish to JetBrains Marketplace
        if: github.event_name == 'workflow_dispatch'
        run: ./gradlew publishPlugin
        working-directory: intelij-plugin
        env:
          INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
          INTELLIJ_PUBLISH_CHANNEL: 'default'
