name: Build, Test, Verify, and Publish JetBrains Plugin

on:
  push:
    paths:
      - 'intelij-plugin/**'
    branches: [main]
  pull_request:
    paths:
      - 'intelij-plugin/**'
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional)'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: intelij-plugin
      - name: Build with Gradle
        run: ./gradlew buildPlugin
        working-directory: intelij-plugin
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-package
          path: intelij-plugin/build/distributions/*.zip
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: intelij-plugin
      - name: Run tests
        run: ./gradlew test
        working-directory: intelij-plugin

  verify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: intelij-plugin
      - name: Verify plugin
        run: ./gradlew verifyPlugin
        working-directory: intelij-plugin

  publish:
    runs-on: ubuntu-latest
    needs: verify
    if: github.event_name == 'workflow_dispatch'
    environment: production  # This is the protected environment that requires approval
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: intelij-plugin
      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-package
          path: intelij-plugin/build/distributions/
      - name: Publish to JetBrains Marketplace
        run: ./gradlew publishPlugin
        working-directory: intelij-plugin
        env:
          INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
          INTELLIJ_PUBLISH_CHANNEL: 'default'
          VERSION: ${{ github.event.inputs.version }}