name: "Server CI"

on:
  push:
    paths:
      - 'server/**'
    branches: [main]
  workflow_dispatch:
    inputs:
      agent_path:
        description: 'Agent resource path (required when manually triggered)'
        required: false
        type: string
  workflow_run:
    workflows: ["AI Consultant Agent"]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  # Validation job to check if agent_path is provided when manually triggered
  validate-inputs:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check agent path input
        run: |
          if [[ -z "${{ github.event.inputs.agent_path }}" ]]; then
            echo "::error::Agent path is required when manually triggering this workflow. Please provide a valid agent_path input."
            exit 1
          else
            echo "Agent path provided: ${{ github.event.inputs.agent_path }}"
          fi

      # If validation passes, create agent_resource.txt file from the input
      - name: Create agent resource file from input
        run: |
          mkdir -p ./manual_agent_resource
          echo "${{ github.event.inputs.agent_path }}" > ./manual_agent_resource/agent_resource.txt

      # Upload as an artifact for the build-and-deploy job
      - name: Upload agent path as artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent_resource
          path: ./manual_agent_resource/agent_resource.txt
          retention-days: 1

  # This job only runs when triggered by the AI Consultant Agent workflow
  get-artifact-from-workflow:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from triggering workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: agent_resource
          path: ./agent_resources

      - name: Upload artifact for this workflow
        uses: actions/upload-artifact@v4
        with:
          name: agent_resource
          path: ./agent_resources/agent_resource.txt
          retention-days: 1

  build-and-deploy:
    needs: [get-artifact-from-workflow, validate-inputs]
    if: |
      always() && 
      (github.event_name == 'push' || 
      (github.event_name == 'workflow_dispatch' && needs.validate-inputs.result == 'success') || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && needs.get-artifact-from-workflow.result == 'success'))
    runs-on: ubuntu-latest
    environment: production
    env:
      PROJECT_ID: ai-consultant-458311
      REGION: asia-south1
      REPO_NAME: ai-consultant-backend-repo
      SERVICE_NAME: ai-consultant-backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # Create directory for agent resource
      - name: Create directory for agent resource
        run: |
          mkdir -p ./server/agents/ai-consultant-agent/deployment

      # Download the artifact (works for both workflow_run and workflow_dispatch due to previous jobs)
      - name: Download agent resource artifact
        uses: actions/download-artifact@v4
        with:
          name: agent_resource
          path: ./server/agents/ai-consultant-agent/deployment

      # Log the agent resource content for debugging
      - name: Log agent resource
        run: |
          echo "Using agent resource:"
          cat ./server/agents/ai-consultant-agent/deployment/agent_resource.txt

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} ./server

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --memory=256Mi \
            --cpu=0.25 \
            --port=8080 \
            --set-env-vars=AGENT_HOST=$(cat ./server/agents/ai-consultant-agent/deployment/agent_resource.txt)

      # Create a completion signal artifact
      - name: Signal server deployment completion
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          echo "Server deployment completed at $(date)" > server_deployment_complete.txt

      # Upload the completion signal as an artifact
      - name: Upload completion signal
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/upload-artifact@v4
        with:
          name: server_deployment_complete
          path: server_deployment_complete.txt
          retention-days: 1