name: "Server CI"

on:
  push:
    paths:
      - 'server/**'
    branches: [main]
  workflow_dispatch:
  workflow_run:
    workflows: ["AI Consultant Agent"]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  # This job only runs when triggered by the AI Consultant Agent workflow
  get-artifact-from-workflow:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from triggering workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: agent_resource
          path: ./agent_resources

      - name: Upload artifact for this workflow
        uses: actions/upload-artifact@v4
        with:
          name: agent_resource
          path: ./agent_resources/agent_resource.txt
          retention-days: 1

  build-and-deploy:
    needs: get-artifact-from-workflow
    if: ${{ github.event_name != 'workflow_run' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    environment: production
    env:
      PROJECT_ID: ai-consultant-458311
      REGION: asia-south1
      REPO_NAME: ai-consultant-backend-repo
      SERVICE_NAME: ai-consultant-backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # Skip downloading artifact if this job was triggered directly (not by workflow_run)
      - name: Create directory for agent resource
        if: ${{ github.event_name != 'workflow_run' }}
        run: |
          mkdir -p ./server/agents/ai-consultant-agent/deployment
          echo "placeholder" > ./server/agents/ai-consultant-agent/deployment/agent_resource.txt

      # Only download the artifact if this was triggered by workflow_run
      - name: Download agent resource artifact
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: agent_resource
          path: ./server/agents/ai-consultant-agent/deployment

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} ./server

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --memory=256Mi \
            --cpu=0.25 \
            --port=8080 \
            --set-env-vars=AGENT_HOST=$(cat ./server/agents/ai-consultant-agent/deployment/agent_resource.txt)